# visualization_config.py

from dataclasses import dataclass
from typing import Optional, Any, Dict
import hashlib
import math
from pathlib import Path
import matplotlib.patches as patches
import logging

logger = logging.getLogger(__name__)


@dataclass
class VisualizationConfig:
    figure_width: float = 16
    figure_height: float = 10
    min_rect_size: int = 2
    max_rect_size: int = 200
    padding: int = 2
    background_color: str = '#0a283c'
    text_color: str = 'white'
    highlight_color: str = '#ffff00'
    border_color: str = '#646464'
    save_format: str = 'png'
    save_path: Optional[str] = None
    interactive: bool = True


class FileRect:
    def __init__(self, file_data: Dict[str, Any], x: int, y: int, width: int, height: int):
        self.file_data = file_data
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.color = self._calculate_color()
        self.hovered = False
        self.patch: Optional[patches.Rectangle] = None

    def _calculate_color(self) -> str:
        file_path = self.file_data.get('path', '')
        size_bytes = self.file_data.get('size_bytes', 0)
        file_ext = Path(file_path).suffix.lower()

        type_colors = {
            # Text files
            '.txt': '#c8c8ff',
            '.md': '#c8c8ff',
            '.rst': '#c8c8ff',
            '.rtf': '#c8c8ff',
            '.tex': '#c8c8ff',
            '.log': '#c8c8ff',
            '.readme': '#c8c8ff',
            '.changelog': '#c8c8ff',
            '.news': '#c8c8ff',
            '.authors': '#c8c8ff',
            '.license': '#c8c8ff',
            '.copying': '#c8c8ff',
            '.todo': '#c8c8ff',
            '.manifest': '#c8c8ff',
            '.install': '#c8c8ff',

            # Programming languages
            '.py': '#64c896',
            '.pyw': '#64c896',
            '.pyc': '#64c896',
            '.pyo': '#64c896',
            '.pyd': '#64c896',
            '.js': '#ffc864',
            '.jsx': '#ffc864',
            '.ts': '#ffc864',
            '.tsx': '#ffc864',
            '.mjs': '#ffc864',
            '.cjs': '#ffc864',
            '.c': '#96c8ff',
            '.cc': '#96c8ff',
            '.cpp': '#96c8ff',
            '.cxx': '#96c8ff',
            '.c++': '#96c8ff',
            '.h': '#96c8ff',
            '.hpp': '#96c8ff',
            '.hxx': '#96c8ff',
            '.h++': '#96c8ff',
            '.java': '#ff9664',
            '.class': '#ff9664',
            '.jar': '#ff9664',
            '.war': '#ff9664',
            '.ear': '#ff9664',
            '.cs': '#9696ff',
            '.vb': '#9696ff',
            '.fs': '#9696ff',
            '.go': '#64ffff',
            '.rs': '#ff6464',
            '.rb': '#ff6496',
            '.php': '#6496ff',
            '.php3': '#6496ff',
            '.php4': '#6496ff',
            '.php5': '#6496ff',
            '.phtml': '#6496ff',
            '.pl': '#96ff64',
            '.pm': '#96ff64',
            '.perl': '#96ff64',
            '.r': '#64ff96',
            '.rdata': '#64ff96',
            '.rds': '#64ff96',
            '.swift': '#ffff64',
            '.kt': '#ff96ff',
            '.kts': '#ff96ff',
            '.scala': '#ff6464',
            '.groovy': '#96c8ff',
            '.lua': '#6496ff',
            '.m': '#ff9664',
            '.mm': '#ff9664',
            '.pas': '#9696ff',
            '.pp': '#9696ff',
            '.ada': '#96ff64',
            '.adb': '#96ff64',
            '.ads': '#96ff64',
            '.f': '#64ffff',
            '.f90': '#64ffff',
            '.f95': '#64ffff',
            '.f03': '#64ffff',
            '.f08': '#64ffff',
            '.for': '#64ffff',
            '.ftn': '#64ffff',
            '.cob': '#c864ff',
            '.cbl': '#c864ff',
            '.lisp': '#ff6496',
            '.lsp': '#ff6496',
            '.cl': '#ff6496',
            '.scm': '#ff6496',
            '.ss': '#ff6496',
            '.rkt': '#ff6496',
            '.hs': '#96ff64',
            '.lhs': '#96ff64',
            '.ml': '#64ff96',
            '.mli': '#64ff96',
            '.elm': '#64c896',
            '.clj': '#ff6496',
            '.cljs': '#ff6496',
            '.cljc': '#ff6496',
            '.erl': '#ff6464',
            '.hrl': '#ff6464',
            '.ex': '#6496ff',
            '.exs': '#6496ff',
            '.jl': '#96ff64',
            '.dart': '#64c896',
            '.v': '#96c8ff',
            '.vh': '#96c8ff',
            '.sv': '#96c8ff',
            '.svh': '#96c8ff',
            '.vhd': '#96c8ff',
            '.vhdl': '#96c8ff',
            '.tcl': '#ff9664',
            '.tk': '#ff9664',
            '.awk': '#c8c8ff',
            '.sed': '#c8c8ff',
            '.nim': '#ffff64',
            '.nims': '#ffff64',
            '.cr': '#c8c8ff',
            '.zig': '#ff9664',
            '.d': '#ff6464',
            '.di': '#ff6464',
            '.odin': '#64c896',
            '.pony': '#ff6496',
            '.purs': '#96ff64',
            '.elm': '#64c896',
            '.coffee': '#96c8ff',
            '.litcoffee': '#96c8ff',

            # Web technologies
            '.html': '#ff9664',
            '.htm': '#ff9664',
            '.xhtml': '#ff9664',
            '.xml': '#ff9664',
            '.xsl': '#ff9664',
            '.xslt': '#ff9664',
            '.css': '#9696ff',
            '.scss': '#9696ff',
            '.sass': '#9696ff',
            '.less': '#9696ff',
            '.styl': '#9696ff',
            '.stylus': '#9696ff',
            '.json': '#ffc864',
            '.jsonl': '#ffc864',
            '.yaml': '#ffc864',
            '.yml': '#ffc864',
            '.toml': '#ffc864',
            '.ini': '#ffc864',
            '.cfg': '#ffc864',
            '.conf': '#ffc864',
            '.config': '#ffc864',
            '.properties': '#ffc864',
            '.prop': '#ffc864',
            '.env': '#ffc864',
            '.rc': '#ffc864',
            '.profile': '#ffc864',
            '.bashrc': '#ffc864',
            '.zshrc': '#ffc864',
            '.vimrc': '#ffc864',
            '.tmux.conf': '#ffc864',
            '.gitconfig': '#ffc864',
            '.gitignore': '#ffc864',
            '.gitattributes': '#ffc864',
            '.editorconfig': '#ffc864',
            '.htaccess': '#ffc864',
            '.htpasswd': '#ffc864',

            # Shell scripts
            '.sh': '#96ff64',
            '.bash': '#96ff64',
            '.zsh': '#96ff64',
            '.fish': '#96ff64',
            '.csh': '#96ff64',
            '.tcsh': '#96ff64',
            '.ksh': '#96ff64',
            '.dash': '#96ff64',
            '.bat': '#96ff64',
            '.cmd': '#96ff64',
            '.ps1': '#96ff64',
            '.psm1': '#96ff64',
            '.psd1': '#96ff64',

            # Images
            '.jpg': '#ff6496',
            '.jpeg': '#ff6496',
            '.png': '#ff6496',
            '.gif': '#ff6496',
            '.bmp': '#ff6496',
            '.tiff': '#ff6496',
            '.tif': '#ff6496',
            '.webp': '#ff6496',
            '.ico': '#ff6496',
            '.svg': '#ff6496',
            '.eps': '#ff6496',
            '.ps': '#ff6496',
            '.ai': '#ff6496',
            '.psd': '#ff6496',
            '.xcf': '#ff6496',
            '.raw': '#ff6496',
            '.cr2': '#ff6496',
            '.nef': '#ff6496',
            '.dng': '#ff6496',
            '.heic': '#ff6496',
            '.heif': '#ff6496',
            '.avif': '#ff6496',
            '.jp2': '#ff6496',
            '.j2k': '#ff6496',
            '.jpf': '#ff6496',
            '.jpx': '#ff6496',
            '.jpm': '#ff6496',
            '.mj2': '#ff6496',

            # Audio
            '.mp3': '#64ff96',
            '.wav': '#64ff96',
            '.flac': '#64ff96',
            '.aac': '#64ff96',
            '.ogg': '#64ff96',
            '.oga': '#64ff96',
            '.wma': '#64ff96',
            '.m4a': '#64ff96',
            '.mp4a': '#64ff96',
            '.aiff': '#64ff96',
            '.aif': '#64ff96',
            '.au': '#64ff96',
            '.snd': '#64ff96',
            '.mid': '#64ff96',
            '.midi': '#64ff96',
            '.kar': '#64ff96',
            '.mpga': '#64ff96',
            '.mp2': '#64ff96',
            '.mp2a': '#64ff96',
            '.m2a': '#64ff96',
            '.m3a': '#64ff96',
            '.oga': '#64ff96',
            '.spx': '#64ff96',
            '.s3m': '#64ff96',
            '.sil': '#64ff96',
            '.uva': '#64ff96',
            '.uvva': '#64ff96',
            '.eol': '#64ff96',
            '.dra': '#64ff96',
            '.dts': '#64ff96',
            '.dtshd': '#64ff96',
            '.lvp': '#64ff96',
            '.pya': '#64ff96',
            '.ecelp4800': '#64ff96',
            '.ecelp7470': '#64ff96',
            '.ecelp9600': '#64ff96',
            '.rip': '#64ff96',
            '.weba': '#64ff96',
            '.aac': '#64ff96',
            '.adp': '#64ff96',
            '.au': '#64ff96',
            '.snd': '#64ff96',
            '.mid': '#64ff96',
            '.midi': '#64ff96',
            '.kar': '#64ff96',
            '.rmi': '#64ff96',

            # Video
            '.mp4': '#96ff64',
            '.avi': '#96ff64',
            '.mov': '#96ff64',
            '.wmv': '#96ff64',
            '.flv': '#96ff64',
            '.webm': '#96ff64',
            '.mkv': '#96ff64',
            '.m4v': '#96ff64',
            '.mpg': '#96ff64',
            '.mpeg': '#96ff64',
            '.mpe': '#96ff64',
            '.ogv': '#96ff64',
            '.qt': '#96ff64',
            '.rm': '#96ff64',
            '.rmvb': '#96ff64',
            '.asf': '#96ff64',
            '.amv': '#96ff64',
            '.mp4v': '#96ff64',
            '.mpv': '#96ff64',
            '.m2v': '#96ff64',
            '.svi': '#96ff64',
            '.3gp': '#96ff64',
            '.3g2': '#96ff64',
            '.mxf': '#96ff64',
            '.roq': '#96ff64',
            '.nsv': '#96ff64',
            '.f4v': '#96ff64',
            '.f4p': '#96ff64',
            '.f4a': '#96ff64',
            '.f4b': '#96ff64',
            '.vob': '#96ff64',
            '.ogm': '#96ff64',
            '.drc': '#96ff64',
            '.gif': '#96ff64',
            '.gifv': '#96ff64',
            '.mng': '#96ff64',
            '.avi': '#96ff64',
            '.mts': '#96ff64',
            '.m2ts': '#96ff64',
            '.ts': '#96ff64',
            '.yuv': '#96ff64',
            '.rmvb': '#96ff64',
            '.viv': '#96ff64',
            '.asf': '#96ff64',
            '.amv': '#96ff64',
            '.m4p': '#96ff64',
            '.m4v': '#96ff64',
            '.mpv': '#96ff64',
            '.mp2': '#96ff64',
            '.mpe': '#96ff64',
            '.mpv': '#96ff64',
            '.m2v': '#96ff64',
            '.svi': '#96ff64',
            '.3gp': '#96ff64',
            '.3g2': '#96ff64',
            '.mxf': '#96ff64',
            '.roq': '#96ff64',
            '.nsv': '#96ff64',

            # Documents
            '.pdf': '#ff6464',
            '.doc': '#6496ff',
            '.docx': '#6496ff',
            '.xls': '#64ff96',
            '.xlsx': '#64ff96',
            '.ppt': '#ff9664',
            '.pptx': '#ff9664',
            '.odt': '#6496ff',
            '.ods': '#64ff96',
            '.odp': '#ff9664',
            '.odg': '#ff6496',
            '.odf': '#c8c8ff',
            '.odb': '#c864ff',
            '.odc': '#c864ff',
            '.odm': '#c864ff',
            '.ott': '#6496ff',
            '.ots': '#64ff96',
            '.otp': '#ff9664',
            '.otg': '#ff6496',
            '.otf': '#c8c8ff',
            '.rtf': '#c8c8ff',
            '.pages': '#6496ff',
            '.numbers': '#64ff96',
            '.keynote': '#ff9664',
            '.wpd': '#6496ff',
            '.wps': '#6496ff',
            '.xps': '#6496ff',
            '.oxps': '#6496ff',
            '.eps': '#ff6496',
            '.ps': '#ff6496',
            '.dvi': '#c8c8ff',
            '.djvu': '#c8c8ff',
            '.djv': '#c8c8ff',
            '.fb2': '#c8c8ff',
            '.epub': '#c8c8ff',
            '.mobi': '#c8c8ff',
            '.azw': '#c8c8ff',
            '.azw3': '#c8c8ff',
            '.kf8': '#c8c8ff',
            '.kfx': '#c8c8ff',
            '.lit': '#c8c8ff',
            '.pdb': '#c8c8ff',
            '.pml': '#c8c8ff',
            '.rb': '#c8c8ff',
            '.tcr': '#c8c8ff',
            '.tr2': '#c8c8ff',
            '.tr3': '#c8c8ff',

            # Archives
            '.zip': '#c864ff',
            '.rar': '#c864ff',
            '.7z': '#c864ff',
            '.tar': '#c864ff',
            '.gz': '#c864ff',
            '.bz2': '#c864ff',
            '.xz': '#c864ff',
            '.lz': '#c864ff',
            '.lzma': '#c864ff',
            '.lzo': '#c864ff',
            '.z': '#c864ff',
            '.Z': '#c864ff',
            '.deb': '#c864ff',
            '.rpm': '#c864ff',
            '.pkg': '#c864ff',
            '.dmg': '#c864ff',
            '.iso': '#c864ff',
            '.img': '#c864ff',
            '.bin': '#c864ff',
            '.toast': '#c864ff',
            '.vcd': '#c864ff',
            '.crx': '#c864ff',
            '.xpi': '#c864ff',
            '.cab': '#c864ff',
            '.msi': '#c864ff',
            '.udf': '#c864ff',
            '.wim': '#c864ff',
            '.swm': '#c864ff',
            '.esd': '#c864ff',
            '.apk': '#c864ff',
            '.ipa': '#c864ff',
            '.deb': '#c864ff',
            '.rpm': '#c864ff',
            '.pkg': '#c864ff',
            '.snap': '#c864ff',
            '.appimage': '#c864ff',
            '.flatpak': '#c864ff',
            '.ace': '#c864ff',
            '.alz': '#c864ff',
            '.arc': '#c864ff',
            '.arj': '#c864ff',
            '.bz': '#c864ff',
            '.cpio': '#c864ff',
            '.ear': '#c864ff',
            '.jar': '#c864ff',
            '.lha': '#c864ff',
            '.lzh': '#c864ff',
            '.mar': '#c864ff',
            '.pea': '#c864ff',
            '.rar': '#c864ff',
            '.s7z': '#c864ff',
            '.shar': '#c864ff',
            '.tbz': '#c864ff',
            '.tbz2': '#c864ff',
            '.tgz': '#c864ff',
            '.tlz': '#c864ff',
            '.txz': '#c864ff',
            '.uu': '#c864ff',
            '.war': '#c864ff',
            '.whl': '#c864ff',
            '.xar': '#c864ff',
            '.zipx': '#c864ff',
            '.zoo': '#c864ff',
            '.zpaq': '#c864ff',
            '.zst': '#c864ff',
            '.zstd': '#c864ff',

            # System files
            '.exe': '#ff6464',
            '.com': '#ff6464',
            '.scr': '#ff6464',
            '.pif': '#ff6464',
            '.application': '#ff6464',
            '.gadget': '#ff6464',
            '.msi': '#ff6464',
            '.msp': '#ff6464',
            '.msu': '#ff6464',
            '.deb': '#ff6464',
            '.rpm': '#ff6464',
            '.pkg': '#ff6464',
            '.snap': '#ff6464',
            '.appimage': '#ff6464',
            '.flatpak': '#ff6464',
            '.run': '#ff6464',
            '.bin': '#ff6464',
            '.bundle': '#ff6464',
            '.app': '#ff6464',
            '.dmg': '#ff6464',
            '.so': '#ff6464',
            '.dylib': '#ff6464',
            '.dll': '#ff6464',
            '.sys': '#ff6464',
            '.drv': '#ff6464',
            '.ko': '#ff6464',
            '.kext': '#ff6464',
            '.o': '#ff6464',
            '.obj': '#ff6464',
            '.lib': '#ff6464',
            '.a': '#ff6464',
            '.la': '#ff6464',
            '.lo': '#ff6464',
            '.lock': '#969696',
            '.tmp': '#969696',
            '.temp': '#969696',
            '.cache': '#969696',
            '.bak': '#969696',
            '.backup': '#969696',
            '.old': '#969696',
            '.orig': '#969696',
            '.swp': '#969696',
            '.swo': '#969696',
            '.DS_Store': '#969696',
            '.Thumbs.db': '#969696',
            '.desktop.ini': '#969696',
            '.directory': '#969696',
            '.url': '#969696',
            '.lnk': '#969696',
            '.alias': '#969696',
            '.webloc': '#969696',
            '.torrent': '#969696',
            '.part': '#969696',
            '.partial': '#969696',
            '.download': '#969696',
            '.crdownload': '#969696',
            '.opdownload': '#969696',
            '.!ut': '#969696',

            # Development files
            '.makefile': '#96c8ff',
            '.cmake': '#96c8ff',
            '.gradle': '#96c8ff',
            '.ant': '#96c8ff',
            '.maven': '#96c8ff',
            '.sbt': '#96c8ff',
            '.bazel': '#96c8ff',
            '.buck': '#96c8ff',
            '.ninja': '#96c8ff',
            '.gyp': '#96c8ff',
            '.gypi': '#96c8ff',
            '.gn': '#96c8ff',
            '.gni': '#96c8ff',
            '.dockerfile': '#96c8ff',
            '.dockerignore': '#96c8ff',
            '.vagrantfile': '#96c8ff',
            '.gemfile': '#96c8ff',
            '.gemspec': '#96c8ff',
            '.podfile': '#96c8ff',
            '.podspec': '#96c8ff',
            '.cartfile': '#96c8ff',
            '.package': '#96c8ff',
            '.project': '#96c8ff',
            '.solution': '#96c8ff',
            '.workspace': '#96c8ff',
            '.xcodeproj': '#96c8ff',
            '.xcworkspace': '#96c8ff',
            '.pbxproj': '#96c8ff',
            '.vcxproj': '#96c8ff',
            '.vbproj': '#96c8ff',
            '.csproj': '#96c8ff',
            '.fsproj': '#96c8ff',
            '.shproj': '#96c8ff',
            '.pyproj': '#96c8ff',
            '.njsproj': '#96c8ff',
            '.sln': '#96c8ff',
            '.suo': '#96c8ff',
            '.user': '#96c8ff',
            '.userprefs': '#96c8ff',
            '.pidb': '#96c8ff',
            '.booproj': '#96c8ff',
            '.svd': '#96c8ff',
            '.mds': '#96c8ff',
            '.mdpolicy': '#96c8ff',
            '.mdproj': '#96c8ff',
            '.mdworkspace': '#96c8ff',
            '.mfbundle': '#96c8ff',
            '.plproj': '#96c8ff',
            '.tmproj': '#96c8ff',
            '.tmproject': '#96c8ff',
            '.mod': '#96c8ff',
            '.sum': '#96c8ff',
            '.work': '#96c8ff',
            '.glide': '#96c8ff',
            '.godeps': '#96c8ff',
            '.vendor': '#96c8ff',
            '.toml': '#96c8ff',
            '.cabal': '#96c8ff',
            '.stack': '#96c8ff',
            '.opam': '#96c8ff',
            '.rebar': '#96c8ff',
            '.mix': '#96c8ff',
            '.lein': '#96c8ff',
            '.boot': '#96c8ff',
            '.shard': '#96c8ff',
            '.nimble': '#96c8ff',
            '.dub': '#96c8ff',
            '.spago': '#96c8ff',
            '.pulp': '#96c8ff',
            '.bower': '#96c8ff',
            '.component': '#96c8ff',
            '.jspm': '#96c8ff',
            '.elm-package': '#96c8ff',
            '.elm-stuff': '#96c8ff',
            '.paket': '#96c8ff',
            '.fake': '#96c8ff',
            '.ionide': '#96c8ff',
            '.fsproj': '#96c8ff',
            '.targets': '#96c8ff',
            '.props': '#96c8ff',
            '.nuspec': '#96c8ff',
            '.packages': '#96c8ff',
            '.config': '#96c8ff',
            '.settings': '#96c8ff',
            '.editorconfig': '#96c8ff',
            '.eslintrc': '#96c8ff',
            '.jshintrc': '#96c8ff',
            '.jscsrc': '#96c8ff',
            '.babelrc': '#96c8ff',
            '.flowconfig': '#96c8ff',
            '.tern-project': '#96c8ff',
            '.tern-port': '#96c8ff',
            '.watchmanconfig': '#96c8ff',
            '.buckconfig': '#96c8ff',
            '.hgignore': '#96c8ff',
            '.hgtags': '#96c8ff',
            '.bzrignore': '#96c8ff',
            '.cvsignore': '#96c8ff',
            '.svnignore': '#96c8ff',
            '.tfignore': '#96c8ff',
            '.p4ignore': '#96c8ff',
            '.fossil-settings': '#96c8ff',
            '.hgrc': '#96c8ff',
            '.hgignore': '#96c8ff',
            '.hgtags': '#96c8ff',
            '.bzrignore': '#96c8ff',
            '.cvsignore': '#96c8ff',
            '.svnignore': '#96c8ff',
            '.tfignore': '#96c8ff',
            '.p4ignore': '#96c8ff',
            '.fossil-settings': '#96c8ff',

            # No extension
            '': '#969696',
        }

        base_color = type_colors.get(file_ext)
        if base_color is None:
            # Generate deterministic random color based on file_ext string
            if file_ext == '':
                base_color = '#969696'  # fallback for no extension
            else:
                # Hash extension to get a reproducible seed
                h = hashlib.md5(file_ext.encode('utf-8')).hexdigest()
                # Use first 6 hex digits as RGB
                base_color = '#' + h[:6]

        # Brightness adjustment as before
        if size_bytes > 0:
            log_size = math.log10(max(size_bytes, 1))
            brightness_factor = min(1.5, 0.5 + (log_size / 10))
            hex_color = base_color.lstrip('#')
            rgb = tuple(int(hex_color[i:i + 2], 16) for i in (0, 2, 4))
            brightened_rgb = tuple(min(255, int(c * brightness_factor)) for c in rgb)
            color = f'#{brightened_rgb[0]:02x}{brightened_rgb[1]:02x}{brightened_rgb[2]:02x}'
        else:
            color = base_color

        return color

    def contains_point(self, x: float, y: float) -> bool:
        return (self.x <= x <= self.x + self.width and
                self.y <= y <= self.y + self.height)

    def create_patch(self) -> patches.Rectangle:
        color = self.color
        if self.hovered:
            hex_color = color.lstrip('#')
            rgb = tuple(int(hex_color[i:i + 2], 16) for i in (0, 2, 4))
            brightened_rgb = tuple(min(255, c + 50) for c in rgb)
            color = f'#{brightened_rgb[0]:02x}{brightened_rgb[1]:02x}{brightened_rgb[2]:02x}'

        # No visible border because spacing gives visual separation
        patch = patches.Rectangle(
            (self.x, self.y), self.width, self.height,
            facecolor=color,
            edgecolor=(0, 0, 0, 0),  # fully transparent edge
            linewidth=0
        )

        logger.debug(f"create_patch: ({self.x},{self.y}) {self.width}x{self.height}, color={color}")

        self.patch = patch
        return patch